### ISSUE TITLE
Doesn't work with Live Preview

### ISSUE THREAD

**Issue by MarkQueppet** [mrjackphil/obsidian-jump-to-link#27] opened 2021-12-19 20:37 UTC
Hi, I cannot seem to get this plugin working with live preview. Is this something that will be worked on? It would be amazing to use jump to link and jump anywhere in the WYSIWYG editor.

**Comment by mrjackphil** [comment] 2021-12-20 05:45
@MarkQueppet I would like to work on this but didn't have much time last half of the year. So, no promises but I'm keeping this in mind.

**Comment by MarkQueppet** [comment] 2021-12-20 17:13
@mrjackphil hey man totally get it. Am happy to talk about compensation if there's any way to get you to prioritize. I value this plugin a lot and there's two additional features I'd love for this plugin to have. If you're interested in discussing, please just let me know the best way to get in contact with you.

**Comment by fakeharxy** [comment] 2022-01-18 15:35
I would also talk about compensation - can barely use Obsidian without it 😄

**Comment by trey2000** [comment] 2022-01-22 21:41
> @MarkQueppet I would like to work on this but didn't have much time last half of the year. So, no promises but I'm keeping this in mind.

Totally understand - i join the previous two commenters and would like to ask you what you need in order to prioritise this. Happy to donate to the cause.

Thanks!

**Comment by mrjackphil** [comment] 2022-01-25 08:00
If only there is a way to get a full-time job by making obsidian plugins :)
Or to get a part-time job which will pay my monthly bills. 

My current full-time job needs a lot of attention from my side. [My expand plugin needs attention, too](https://github.com/mrjackphil/obsidian-text-expand/issues/59#issuecomment-1020809347). I hope I'll stop searching for excuses and will start working on plugins.

**Comment by mrjackphil** [comment] 2022-03-15 12:50
Should be fixed in **v0.3.0**

**Closed as completed by mrjackphil** 2022-03-15 12:50 UTC

**Comment by mrjackphil** [comment] 2022-03-15 12:52
Big shoutout to @tadashi-aikawa ! Your developments helped a lot!
