### ISSUE TITLE
Feature Request: Jump to Dataview-rendered note links

### ISSUE THREAD

**Issue by frankreporting** [mrjackphil/obsidian-jump-to-link#19] opened 2021-06-06 02:30 UTC
Love this plugin for bringing Vimium-like functionality to Obsidian's preview mode. I just discovered that it doesn't recognize notes/links rendered via the Dataview, another great plugin. Is it feasible to have Jump to Link "see" rendered lists and tables and find the links within them?

**Comment by aleksey-rowan** [comment] 2023-10-30 02:09
This looks like a duplicate of https://github.com/mrjackphil/obsidian-jump-to-link/issues/28.

**Comment by frankreporting** [comment] 2023-10-30 02:11
So it is. I'll close.

**Closed as not planned** 2023-10-30 02:12 UTC
